language: python
python:
    - "2.7"
    - "3.6"
install:
    - python setup.py install
script:
    - python setup.py test
    - which listed-dev
    - which listed-prod
    - python -c 'from listed.server import prod, dev'
